Resources:
  GroupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: group_id
          AttributeType: S
      KeySchema:
        - AttributeName: group_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
