[package]
name = "models"
version = "0.1.0"
authors = ["val500 <varun.valada@gmail.com>"]
edition = "2018"

[dependencies]
dynomite = "0.7"
futures = "0.35"
tokio = { version = "0.2", features = ["rt-core"] }
rusoto_core = "0.43"
rusoto_dynamodb = "0.43"

